apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-{{.Values.name}}
  annotations:
    #kubernetes.io/ingress.global-static-ip-name: {{.Values.staticIp}}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: test.ingress.com
    http:
      paths:
      - path: /{{.Values.servicePort}}
        backend:
          serviceName: nodeport-{{.Values.name}}
          servicePort: {{.Values.servicePort}}
#  backend:
#    serviceName: nodeport-{{.Values.name}}
#    servicePort: {{.Values.servicePort}}
