apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-{{.Values.name}}
  annotations:
    #kubernetes.io/ingress.global-static-ip-name: {{.Values.staticIp}}
spec:
  backend:
    serviceName: nodeport-{{.Values.name}}
    servicePort: {{.Values.servicePort}}
