apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-{{.Values.name}}
  annotations:
    #kubernetes.io/ingress.global-static-ip-name: {{.Values.staticIp}}
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  paths:
    - path: /{.Values.github_login}}
      backend:
        serviceName: nodeport-{{.Values.name}}
        servicePort: {{.Values.servicePort}}
#  backend:
#    serviceName: nodeport-{{.Values.name}}
#    servicePort: {{.Values.servicePort}}
